### ISSUE TITLE
Pure OCaml implementation?

### ISSUE THREAD

**Issue by anuragsoni** [314eter/ocaml-hpack#1]
Hello,

this is more a question than an issue. I noticed that before the latest commit there was a pure OCaml implementation with corresponding lwt/async wrappers for IO. I was curious about how do you envision this library to be integrated into an HTTP/2 implementation? Are you planning on `async` support? or do you plan to only support lwt?

I am interested in helping work towards a protocol implementation and i've been making slow progress (I've worked on the frame serializer/deserialized so far). I was going to model my approach on how `cohttp` and `httpaf` work by providing a core library that works against a buffer (bigstringaf/bigstring in httpaf i think) and let the `async` and `lwt` control the IO logic. 

Best,
Anurag

**Comment by 314eter** [comment]
I was working on an HTTP/2 implementation too, but without buffering, so that's what this hpack implementation is currently doing. The IO/buffering logic is completely left to the user.

I decided to drop Async support because the exception handling is not compatible with Lwt.

**Comment by anuragsoni** [comment]
wouldn't this make it a little difficult to embed into `cohttp` and `httpaf`? Or I suppose what i'm really asking is how do you see this being used with the current libraries in the ecosystem?

**Comment by 314eter** [comment]
I'm not sure yet how it should be used. I changed the exception handling to `result` types, so it's again compatible with both Async and Lwt.

I don't know how easy it is to use with an angstrom parser. But HTTP/2 is a binary protocol that doesn't need backtracking, so I don't think it's necessary to use angstrom.

**Comment by anuragsoni** [comment]
I agree that there is no backtracking needed for the HTTP/2 protocol, I had started with angstrom/faraday simply because that's what I had seen being used in `httpaf`. Another reason was that it made the implementation easy to understand (at least in my opinion), while leaving enough flexibility to not be opinionated about IO. I also get incremental parsing for not much more work. Angstrom provides an `Unbuffered` module which could be used to parse the frame_header and then it could hand off the rest of the decoding to the `hpack` decoder? 

https://github.com/anuragsoni/h2/blob/master/h2/lib/reader.ml#L21 (I haven't used the zero-copy unbufferred interface yet but that should be straightforward to plug in)

That said, it'd be nice to find a way to collaborate so we don't end up re-doing a lot of the same things :smile:
